<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    public $timestamps = false;

    public $hidden = ['id'];

    public $fillable = ['nombre', 'slug', 'descripcion', 'categoriaPadre', 'posicion'];

    use HasFactory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $maxPosition = static::max('posicion');
            $model->posicion = $maxPosition ? $maxPosition + 1: 1;
        });
    }

    public function imagenes()
    {
        return $this->morphMany(Imagen::class, 'imageable');
    }

    public function productos()
    {
        return $this->hasMany(Producto::class);
    }

    public function categoriasHijas()
    {
        return $this->hasMany(Categoria::class, 'categoriaPadre', 'id');
    }

    public function categoriaPadre()
    {
        return $this->belongsTo(Categoria::class, 'categoriaPadre', 'id');
    }
}
